### ISSUE TITLE
Install on OSX Catalina.

### ISSUE THREAD

**Issue by jvmvik** [castwide/readapt#4] opened 2019-11-14 17:08 UTC
macOS Catalina 10.15.1
$>ruby --version
ruby 2.5.3p105

$>gem install readapt
`
Fetching: backport-1.1.2.gem (100%)
Successfully installed backport-1.1.2
Fetching: thor-0.20.3.gem (100%)
Successfully installed thor-0.20.3
Fetching: readapt-0.8.0.gem (100%)
Building native extensions. This could take a while...
ERROR:  Error installing readapt:
        ERROR: Failed to build gem native extension.

    current directory: /Users/vicben01/.rvm/gems/ruby-2.5.3/gems/readapt-0.8.0/ext/readapt
/Users/vicben01/.rvm/rubies/ruby-2.5.3/bin/ruby -r ./siteconf20191114-59641-1nn7hhg.rb extconf.rb
creating Makefile

current directory: /Users/vicben01/.rvm/gems/ruby-2.5.3/gems/readapt-0.8.0/ext/readapt
make "DESTDIR=" clean

current directory: /Users/vicben01/.rvm/gems/ruby-2.5.3/gems/readapt-0.8.0/ext/readapt
make "DESTDIR="
compiling breakpoints.c
compiling frame.c
compiling hash_table.c
compiling inspector.c
In file included from inspector.c:4:
In file included from ./threads.h:6:
./stack.h:12:3: error: typedef redefinition with different types ('struct stack_struct' vs 'struct __darwin_sigaltstack')
} stack_t;
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_sigaltstack.h:48:33: note: previous definition is here
typedef _STRUCT_SIGALTSTACK     stack_t; /* [???] signal stack */
                                ^
1 error generated.
make: *** [inspector.o] Error 1

make failed, exit code 2
`

**Comment by castwide** [comment] 2019-11-14 19:43
Confirmed. The problem is a header name conflict specific to MacOS. I'll have it fixed in a patch release shortly.

**Comment by castwide** [comment] 2019-11-14 20:07
Fix released in v0.8.1.

**Comment by jvmvik** [comment] 2019-11-15 19:27
👍 Awesome ! Issue resolved

`
>gem install readapt
Fetching: readapt-0.8.1.gem (100%)
Building native extensions. This could take a while...
Successfully installed readapt-0.8.1
1 gem installed
>ruby --version
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
`

**Closed** 2019-11-15 19:28 UTC
